# Generated by Django 2.2.1 on 2019-05-31 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Заголовок', 'verbose_name_plural': 'Заголовки'},
        ),
    ]
