# Generated by Django 2.2.1 on 2019-05-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0002_auto_20190601_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
