# Generated by Django 2.2.1 on 2019-05-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0003_auto_20190601_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=150)),
                ('naz', models.CharField(blank=True, max_length=100)),
                ('modal', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=50)),
                ('text', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('age', models.CharField(blank=True, max_length=2)),
                ('rost', models.CharField(blank=True, max_length=3)),
                ('ves', models.CharField(blank=True, max_length=3)),
                ('hvat', models.CharField(blank=True, max_length=10)),
                ('model', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
