# Generated by Django 2.2.1 on 2019-05-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0004_image_models_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naz', models.CharField(blank=True, max_length=1500)),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
    ]
