# Generated by Django 2.2.1 on 2019-05-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0006_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contract',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
