# Generated by Django 2.2.1 on 2019-05-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0007_team_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='modal',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
